[package]
name = "angrapa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
futures = "0.3.28"
regex = "1.9.1"
shiplift = "0.7.0"
tokio = { version = "1.29.1", features = ["full"] }
