[common]
# TODO change for actual ecsc
start = "2023-10-13T14:00:00Z"
format = 'ECSC_\w{32}'
tick = 180
flag_validity = 5
services = [
    "Service 1 Checker",
]
services_without_flagid = [
    "twotask",
    "threetask"
]
[common.rename]
"Service 1 Checker" = "onetask"

own = '172.16.20.1'
nop = '172.16.1.1'

[manager]
submitter_name = 'faust'
fetcher_name = 'faust'
[manager.submitter]
host = '192.168.100.50:31337'
[manager.fetcher]
teams = 'https://ad.ctf.ecsc.no/competition/teams.json'
scoreboard = 'https://ad.ctf.ecsc.no/competition/scoreboard-v2/scoreboard_current.json'
format = '172.16.{x}.1'

[runner]
http_server = "[::]:8000"
ws_server = "[::]:8001"

[database]
username = "angrepa"
password = "a"
host = "localhost"
db = "angrepa"
