[common]
#start = "2023-10-25T08:00:00Z"
start = "2023-10-20T08:00:00Z"
format = 'ECSC_\w{32}'
tick = 180
flag_validity = 5
services = [
    "Service 1 Checker",
]
services_without_flagid = [
    "twotask",
    "threetask"
]
[common.rename]
"Service 1 Checker" = "onetask"

#own = '172.16.20.1'
own = '129.241.150.151'
#nop = '172.16.1.1'

[manager]
submitter_name = 'faust'
fetcher_name = 'faust'
[manager.submitter]
host = '129.241.150.151:31337'
[manager.fetcher]
teams = 'https://ad.ctf.ecsc.no/competition/teams.json'
scoreboard = 'https://ad.ctf.ecsc.no/competition/scoreboard-v2/scoreboard_current.json'

# yeah... use ecsc_hosts in /etc/hosts
format = 'lol_{x}'
#format = '172.16.{x}.1'

[runner]
http_server = "[::]:8000"
ws_server = "[::]:8001"

[database]
username = "angrepa"
password = "a"
host = "localhost"
db = "angrepa"
