[common]
# this is one hour before network opens!
start = "2023-07-22T12:00:00Z"
format = 'ENO[A-Za-z0-9+\/=]{48}'
#webhook = 'https://discord.com/api/webhooks/1131298841619083314/dRksylbBiaETqhlLLJ7KwQ-h0gtMcl8XbBFLyPYYPybogSAAL5bJfgUh2zEW11lhyMql'
tick = 60
oldest_possible_flags = 600
services = [
    "asocialnetwork",
    "bollwerk",
    "granulizer",
    "oldschool",
    "phreaking",
    "steinsgate",
    "yvm",
]

[manager]
submitter_name = 'faust'
fetcher_name = 'enowars'
[manager.submitter]
host = '10.0.13.37:1337'
[manager.fetcher]
endpoint = 'https://7.enowars.com/scoreboard/attack.json'
ips = 'https://7.enowars.com/api/data/ips'

[runner]
http_server = "0.0.0.0:8000"

[database]
username = "angrepa"
password = "a"
host = "localhost"
db = "angrepa"
