[common]
# this is one hour before network opens!
start = "2023-07-22T12:00:00Z"
format = 'ENO[A-Za-z0-9+\/=]{48}'
webhook = 'https://discord.com/api/webhooks/1131298841619083314/dRksylbBiaETqhlLLJ7KwQ-h0gtMcl8XbBFLyPYYPybogSAAL5bJfgUh2zEW11lhyMql'
tick = 60

[manager]
http_listener = "0.0.0.0:8000"
tcp_listener = "0.0.0.0:8001"
submitter_name = 'faust'
fetcher_name = 'enowars'
[manager.submitter]
host = '10.0.13.37:1337'
header_suffix = "\n\n"
[manager.fetcher]
endpoint = 'https://7.enowars.com/scoreboard/attack.json'
ips = 'https://7.enowars.com/api/data/ips'

[runner]
http_server = "0.0.0.0:8888"

[database]
username = "postgres"
password = "pass1"
host = "localhost"
db = "diesel_demo"