[common]
start = "2023-09-23T13:00:00Z"
format = 'FAUST_[A-Za-z0-9/+]{32}'
# https://2023.faustctf.net/information/rules/
tick = 180 # 3min
flag_validity = 5
services = [
]

own = "fd66:666:901::2"
nop = "fd66:666:1::2"

[manager]
submitter_name = 'faust'
fetcher_name = 'faust'
[manager.submitter]
host = 'submission.faustctf.net:666'
[manager.fetcher]
teams = 'https://2023.faustctf.net/competition/teams.json'
scoreboard = 'https://2023.faustctf.net/competition/scoreboard-v2/scoreboard_current.json'
format = 'fd66:666:{x}::2'

[runner]
http_server = "0.0.0.0:8000"
ws_server = "0.0.0.0:8001"

[database]
username = "angrepa"
password = "a"
host = "localhost"
db = "angrepa"
