[common]
start = "2023-08-31T13:40:00Z"
format = "ECSC_[A-Za-z0-9\\+/]{32}"
tick = 30
flag_validity = 10
# service names, if renamed, then the name they are renamed to
services = ["testservice", "otherservice"]
# optional
nop = "10.0.1.1"
own = "10.0.4.1"

#[common.rename]
#"a really stupid name" = "epicname"

[manager]
submitter_name = 'dummy'
fetcher_name = 'dummy'
[manager.submitter]
[manager.fetcher]

[runner]
http_server = "[::]:8000"
ws_server = "[::]:8001"

[database]
username = "angrepa"
password = "a"
host = "localhost"
db = "angrepa"
