[common]
start = "2023-07-18T12:00:00Z"
format = "ECSC_[A-Za-z0-9\\+/]{32}"
tick = 15

[manager]
http_listener = "0.0.0.0:8000"
tcp_listener = "0.0.0.0:8001"
submitter_name = 'dummy'
fetcher_name = 'enowars'
[manager.submitter]
host = 'localhost:1337'
header_suffix = "\n\n"
[manager.fetcher]
endpoint = 'https://7.enowars.com/scoreboard/attack.json'

[runner]
http_server = "0.0.0.0:8888"
