[common]
start = "2023-07-18T12:00:00Z"
format = "ECSC_[A-Za-z0-9\\+/]{32}"
tick = 20
oldest_possible_flags = 200
services = ["testservice"]

[manager]
submitter_name = 'dummy'
fetcher_name = 'dummy'
[manager.submitter]
[manager.fetcher]

[runner]
http_server = "0.0.0.0:8000"

[database]
username = "angrepa"
password = "a"
host = "localhost"
db = "angrepa"
