[common]
start = "2023-07-18T12:00:00Z"
format = "ECSC_[A-Za-z0-9\\+/]{32}"
tick = 5

[manager]
submitter_name = 'dummy'
fetcher_name = 'dummy'
[manager.submitter]
host = 'localhost:1337'
[manager.fetcher]
endpoint = 'https://7.enowars.com/scoreboard/attack.json'
ips = 'https://7.enowars.com/api/data/ips'

[runner]
http_server = "0.0.0.0:8000"

[database]
username = "angrepa"
password = "a"
host = "localhost"
db = "angrepa"