[common]
start = "2023-08-22T12:20:00Z"
format = "ECSC_[A-Za-z0-9\\+/]{32}"
tick = 10
flag_validity = 10
# service names, if renamed, then the name they are renamed to
services = ["testservice", "a really stupid name"]
# optional
nop = "10.0.1.1"

#[common.rename]
"a really stupid name" = "epicname"

[manager]
submitter_name = 'dummy'
fetcher_name = 'dummy'
[manager.submitter]
[manager.fetcher]

[runner]
http_server = "0.0.0.0:8000"

[database]
username = "angrepa"
password = "a"
host = "localhost"
db = "angrepa"
