name: macOS
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: build
        run: cargo build
      - name: test
        run: cargo test -- --nocapture --test-threads=1
      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          args: --all-targets --all-features --no-deps -- -D warnings
          token: ${{ secrets.GITHUB_TOKEN }}
